### PR TITLE
Record job execution errors on retries

### LINKED ISSUE #227: Record job errors when retrying
Currently a job may be retried multiple times resulting in varying error messages, but all error messages are not stored.

Suggestion: store the error messages when retrying, and return a list of errors instead of a single error message if the job ultimately fails. This would help with troubleshooting possible issues.

Related to #220

### PR DESCRIPTION
**Pull request by nanuuki**
Resolve #227

### CODE REVIEW

File: jobs/jobs.go [hunk 1]
```diff
@@ -32,6 +33,7 @@ type Job struct {
 	Type                   string         `gorm:"column:type"`
 	State                  State          `gorm:"column:state;default:INIT"`
 	Error                  string         `gorm:"column:error"`
+	Errors                 pq.StringArray `gorm:"column:errors;type:text[]"`
```
Comment (nanuuki) [inline jobs/jobs.go:36]: Left the `Error` field intact, as that's a quick way to check if the final execution ended in an error. Thoughts on `Errors` vs. `ErrorHistory`, other suggestions?

**Review by latenssi — APPROVED** [review]
